/**
 * Friend codes (T7.6): 6 characters from 2-9 and A-H, generated by the database
 * (users.friend_code). Input is forgiving: any case, spaces and dashes are ignored.
 */

export const FRIEND_CODE_PATTERN = /^[2-9A-H]{6}$/;

/** The canonical code for what a player typed, or null when it can't be a code. */
export function normalizeFriendCode(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const code = raw.replace(/[\s-]/g, "").toUpperCase();
  return FRIEND_CODE_PATTERN.test(code) ? code : null;
}
