/**
 * Screen-name rules (plan T6.7), pure so they can be tested and shared.
 * Names are public on leaderboards, so they are generated by default
 * ("bouncy-otter-42") and a kid may pick their own within these rules.
 */
import { englishDataset, englishRecommendedTransformers, RegExpMatcher } from "obscenity";

// Six letters at most each, so "adjective-animal-NN" always fits in 16 characters.
const ADJECTIVES = [
  "bouncy",
  "brave",
  "bright",
  "bubbly",
  "cheeky",
  "chirpy",
  "clever",
  "comfy",
  "cosmic",
  "crafty",
  "dizzy",
  "dreamy",
  "eager",
  "fizzy",
  "fluffy",
  "frosty",
  "funky",
  "fuzzy",
  "giddy",
  "gentle",
  "glossy",
  "golden",
  "groovy",
  "happy",
  "humble",
  "jazzy",
  "jolly",
  "jumpy",
  "kind",
  "lively",
  "lucky",
  "mellow",
  "merry",
  "mighty",
  "nifty",
  "peppy",
  "perky",
  "plucky",
  "proud",
  "quick",
  "quirky",
  "rapid",
  "rosy",
  "shiny",
  "silly",
  "sleepy",
  "snappy",
  "snug",
  "sparky",
  "speedy",
  "spicy",
  "sunny",
  "super",
  "swift",
  "tidy",
  "turbo",
  "witty",
  "zany",
  "zesty",
  "zippy",
];
const ANIMALS = [
  "alpaca",
  "badger",
  "beaver",
  "bison",
  "bunny",
  "camel",
  "cobra",
  "corgi",
  "crab",
  "dingo",
  "dodo",
  "dragon",
  "eagle",
  "emu",
  "ferret",
  "finch",
  "gecko",
  "goose",
  "hamster",
  "hippo",
  "husky",
  "ibis",
  "iguana",
  "jaguar",
  "koala",
  "lemur",
  "llama",
  "lynx",
  "magpie",
  "marmot",
  "moose",
  "newt",
  "numbat",
  "ocelot",
  "otter",
  "owl",
  "panda",
  "parrot",
  "possum",
  "puffin",
  "quokka",
  "quoll",
  "rabbit",
  "robin",
  "seal",
  "shark",
  "sloth",
  "squid",
  "tapir",
  "tiger",
  "toucan",
  "turtle",
  "walrus",
  "wombat",
  "yak",
  "zebra",
].filter((w) => w.length <= 6);

export const SCREEN_NAME_MIN = 3;
export const SCREEN_NAME_MAX = 16;

export function generateScreenName(random: () => number = Math.random): string {
  const pick = <T>(list: readonly T[]) => list[Math.floor(random() * list.length)]!;
  const number = String(Math.floor(random() * 90) + 10);
  return `${pick(ADJECTIVES)}-${pick(ANIMALS)}-${number}`;
}

export type ScreenNameProblem =
  "too_short" | "too_long" | "bad_characters" | "all_digits" | "not_allowed" | "reserved";

export type ScreenNameCheck =
  { ok: true; name: string } | { ok: false; problem: ScreenNameProblem };

const matcher = new RegExpMatcher({ ...englishDataset.build(), ...englishRecommendedTransformers });

/** The makers' names can't be used, so nobody can pretend to be them. */
const RESERVED = ["james", "tilly", "harvey", "admin", "moderator", "games4james", "official"];

/** Trims and collapses inner spaces; the result is what gets stored. */
export function normaliseScreenName(raw: string): string {
  return raw.trim().replace(/\s+/g, " ");
}

export function checkScreenName(raw: string): ScreenNameCheck {
  const name = normaliseScreenName(raw);
  if (name.length < SCREEN_NAME_MIN) return { ok: false, problem: "too_short" };
  if (name.length > SCREEN_NAME_MAX) return { ok: false, problem: "too_long" };
  // Letters, digits, spaces and hyphens only: no @ or dots, so no emails or URLs.
  if (!/^[\p{L}\p{N}][\p{L}\p{N} -]*$/u.test(name)) return { ok: false, problem: "bad_characters" };
  if (/^[\d -]+$/.test(name)) return { ok: false, problem: "all_digits" };
  const squashed = name.toLowerCase().replace(/[\s-]+/g, "");
  if (matcher.hasMatch(name) || matcher.hasMatch(squashed))
    return { ok: false, problem: "not_allowed" };
  if (RESERVED.some((word) => squashed.includes(word))) return { ok: false, problem: "reserved" };
  return { ok: true, name };
}

/** Friendly copy for each problem, in the family voice. */
export const SCREEN_NAME_MESSAGES: Record<
  ScreenNameProblem | "taken" | "too_many_changes",
  string
> = {
  too_short: `Names need at least ${SCREEN_NAME_MIN} letters.`,
  too_long: `Names can be up to ${SCREEN_NAME_MAX} letters.`,
  bad_characters: "Use letters, numbers, spaces and dashes only.",
  all_digits: "Add some letters, not just numbers.",
  not_allowed: "That name isn't allowed here. Try another one.",
  reserved: "That name belongs to the Games4James team. Try another one.",
  taken: "That one's taken, try another.",
  too_many_changes: "You can change your name 3 times a month. Try again later.",
};
